### ISSUE TITLE
IE9 and slide and flex-caption with width:auto

### ISSUE THREAD

**Issue by samspade** [woothemes/FlexSlider#1006]
Hi, 

I applied the flexslider to my site and used the p.flex-caption CSS to add captions. To make the captions more presentable I added the following styles 
```css
.flex-caption{position:absolute;width: auto;color:#fff;z-index: 50;top: 25px;margin-left: 25px;padding:10px;}
```

The addition of width:auto has the desired effect of making the div resize to the width of the text, but in IE9 the first slide is fine, but the remaining slides appear squashed and then on hovering over the slider the div pops to the correct width.

 There are no changes to the CSS that I can see and changing the transition option to fade solves the issue.
