### ISSUE TITLE
safari - smoothHeight - doesn't work

### ISSUE THREAD

**Issue by andrejpavlovic** [woothemes/FlexSlider#1158]
When smoothHeight is enabled, the initial height of the flexslider is set to 0px because none of the images are loaded yet. Only once the user clicks somewhere on the screen, is the slider height refreshed with a valid height.

I threw something together quickly to solve this issue:

jquery.flexslider.js
```javascript
      smoothHeight: function(dur) {
        if (!vertical || fade) {
          var $obj = (fade) ? slider : slider.viewport,
              height = slider.slides.eq(slider.animatingTo).height();

          if (!height) {
            setTimeout(function() {
              methods.smoothHeight(dur);
            }, 100);
          } else {
            if (!$obj.data('height-set')) {
              $obj.addClass('flex-notransition');
            }

            (dur) ? $obj.animate({"height": height}, dur) : $obj.height(height);

            $obj[0].offsetHeight;
            $obj.removeClass('flex-notransition');
            $obj.data('height-set', true);
          }
        }
      },
```

flexslider.css
```css
.flex-notransition {
  -webkit-transition: none !important;
  -moz-transition: none !important;
  -o-transition: none !important;
  -ms-transition: none !important;
  transition: none !important;
}
```
